include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    camel_case_types: true
    public_member_api_docs: false
