name: strategem
description: "Strategem is a strategic gaming platform inspired by game theory, featuring classic puzzles, multiplayer battles, and solo challenges to test and sharpen your mind."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
